/* checklist SQL


 1. ALTER TABLE
2. CREATE INDEX
3. INSERT INTO
4. UPDATE
5. DELETE
6. SELECT-FROM-WHERE
7. BETWEEN
8. IN
9. LIKE
10. IS NULL ou IS NOT NULL
11. INNER JOIN
12. MAX
13. MIN
14. AVG
15. COUNT
16. LEFT ou RIGHT ou FULL OUTER JOIN
17. SUBCONSULTA COM OPERADOR RELACIONAL
18. SUBCONSULTA COM IN
19. SUBCONSULTA COM ANY
20. SUBCONSULTA COM ALL
21. ORDER BY
22. GROUP BY
23. HAVING
24. UNION ou INTERSECT ou MINUS
25. CREATE VIEW
26. GRANT / REVOKE*/



